name: Publish Javadocs

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish Maven Package"]
    types: [completed]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish_javadocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Generate Javadocs
        run: mvn -B verify -Pgithub

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/site/apidocs

  deploy_pages:
    needs: publish_javadocs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v4
